# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk13

services:
  - postgresql

# используем режим обычного пользователя для сборки проекта.
sudo: false

before_install:
  - psql -c 'create database shortcut;' -U postgres


# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - roman.mozhaev@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

env:
  global:
    - CODECOV_TOKEN="2d4c549c-5ef4-4763-a0b6-39d4058ce561"
